#!/usr/bin/env bash

# copied from https://github.com/ThePrimeagen

if [[ -z $DEVPATHS ]]; then
    DEVPATHS=`fd --exact-depth=3 --base-directory ~/progdev/`
fi

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(printf "%s\n" "${DEVPATHS[@]}" | fzf | awk '{print "/home/crang/progdev/" $1}')
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
